### ISSUE TITLE
Use of write.table and textConnection in dbWriteTable leads to creation of global variable

### ISSUE THREAD

**Issue by awchisholm** [hannesmuehleisen/clickhouse-r#8]
This code

    write.table(value, textConnection("value_str", open="w"), sep="\t", row.names=F, col.names=F)
    value_str2 <- paste0(get("value_str"), collapse="\n")

Creates a global variable called "value_str" which can cause subsequent calls to fail with the error 

    Error in textConnection("value_str", open = "w") : 
        cannot change value of locked binding for 'value_str'

A simple workaround would be to use a random name and delete it after use. A more sophisticated fix would be to keep the working private.

**Comment by hannesmuehleisen** [comment]
Happy to review a PR

**Comment by hannesmuehleisen** [comment]
merged thanks
